---
version: 1
dependencies:
  galaxy: build-el8/requirements.yml
  python: build-el8/requirements.txt
  system: build-el8/bindep.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - ADD certs /etc/pki/ca-trust/source/anchors
    - RUN update-ca-trust
    - ADD run.sh /run.sh
    - CMD /run.sh
    - USER 1000
    - RUN git lfs install
