---
version: 3
images:
  base_image:
    name: quay.io/rockylinux/rockylinux:9
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.*
  ansible_runner:
    package_pip: ansible-runner
  galaxy: build/requirements-lint.yml
  python: build/requirements-lint.txt
  system: build/bindep.txt
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
  prepend_builder:
    - RUN dnf install -y epel-release
  prepend_final:
    - RUN dnf install -y epel-release
  append_final:
    - ADD certs /etc/pki/ca-trust/source/anchors
    - RUN update-ca-trust
    - RUN git lfs install --system
    - ENTRYPOINT []
    - ENV SHELL /bin/bash
