---
collections:
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: awx.awx
  - name: azure.azcollection
  - name: community.crypto
  - name: community.general
  - name: community.kubernetes
  - name: community.vmware
    version: "<3.0.0"
  - name: community.zabbix
  - name: kubernetes.core
  - name: netapp.ontap
  - name: redhatinsights.insights
  - name: vmware.vmware_rest
