---
roles:
  - src: geerlingguy.php
    version: 3.7.0
  - src: geerlingguy.php-versions
    version: 4.0.2
  - src: geerlingguy.ansible
    version: 2.0.1
  - src: geerlingguy.repo-epel
    version: 1.2.4
  - src: geerlingguy.repo-remi
    version: 1.2.0
  - src: geerlingguy.nginx
    version: 2.7.0
  - src: geerlingguy.redis
    version: 1.6.0
  - src: geerlingguy.postgresql
    version: 2.0.1
  - src: geerlingguy.jenkins
    version: 4.3.0
  - src: geerlingguy.java
    version: 1.10.0
  - src: geerlingguy.ssh-chroot-jail
    version: 1.4.4
  - src: geerlingguy.php-xdebug
    version: 3.0.0
  - src: geerlingguy.clamav
    version: 1.3.2
collections:
  - awx.awx
  - amazon.aws
  - ansible.posix
  - ansible.windows
  - awx.awx
  - azure.azcollection
  # - community.vmware
  - google.cloud
  - kubernetes.core
  - openstack.cloud
  - ovirt.ovirt
  - redhatinsights.insights
  # - theforeman.foreman
  - community.aws
  - community.general
