name: "Build container from arbitrary repo / ref"
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'The receptor repository to build from.'
        required: true
        default: 'ansible/awx-ee'
      ref:
        description: 'The ref to build. Can be a branch or any other valid ref.'
        required: true
        default: 'devel'
      receptor_image:
        description: 'The receptor image to use for the build'
        required: true
        default: 'quay.io/ansible/receptor:devel'
      tag:
        description: 'The tag for the container.'
        required: true
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Login To ghcr.io
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push image
        env:
          DOCKER_BUILDKIT: 1
          TAG: ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag }}
          RECEPTOR_IMAGE: ${{ github.event.inputs.receptor_image }}
        run: |
          TAG=$(echo $TAG | tr '[A-Z]' '[a-z]')
          tox -e docker -- --tag=$TAG --build-arg RECEPTOR_IMAGE=${RECEPTOR_IMAGE}
          docker push $TAG
